#!/bin/bash
# -----------------------------------------------------------------------------
# File: bu/util_doc.sh
# Author: Generated by GitHub Copilot
# -----------------------------------------------------------------------------
# Description: Utility functions for generating documentation using GitHub Copilot.
# -----------------------------------------------------------------------------
# Check if util_bash is loaded
[[ -z "${BASH_UTILS_LOADED}" ]] && { echo "ERROR: util_bash.sh is not loaded. Please source it before using this script."; exit 1; }

#==============================================================================
# DOCUMENTATION GENERATION FUNCTIONS
#==============================================================================

# -----------------------------------------------------------------------------
# Function: send_to_copilot
# Description: Sends the contents of a file as a prompt to GitHub Copilot
# Usage: send_to_copilot <path_to_prompt_file>
# Parameters:
#   $1 - Path to the prompt file
# Returns:
#   0 on success, non-zero on failure
# -----------------------------------------------------------------------------
send_to_copilot() {
    local prompt_file="$1"
    
    # Check if a file path was provided
    if [[ -z "$prompt_file" ]]; then
        err "No prompt file specified. Usage: send_to_copilot <path_to_prompt_file>"
        return 1
    fi
    
    # Check if the file exists
    if [[ ! -f "$prompt_file" ]]; then
        err "Prompt file does not exist: $prompt_file"
        return 1
    fi
    
    info "Sending prompt from file: $prompt_file to GitHub Copilot..."
    
    # Check if GitHub CLI is installed
    if ! command -v gh &> /dev/null; then
        warn "GitHub CLI is not installed or not found in PATH."
        warn "Install it using: brew install gh (macOS) or follow instructions at https://cli.github.com/manual/installation"
        return 1
    fi
    
    # Check if GitHub Copilot CLI extension is installed
    if ! gh extension list | grep -q "copilot"; then
        warn "GitHub Copilot extension for GitHub CLI is not installed."
        warn "Install it using: gh extension install github/gh-copilot"
        return 1
    fi
    
    # Send the file content to GitHub Copilot
    gh copilot suggest < "$prompt_file"
    
    return $?
}

# -----------------------------------------------------------------------------
# If loading is successful this will be executed
# Always makes sure this is the last function call
type list_bash_functions_in_file >/dev/null 2>&1 && list_bash_functions_in_file "$(realpath "$0")" || err "alias is not loaded"
# -----------------------------------------------------------------------------
